/**
 * role-share.js — build the shareable /share/<roleId> URL for a result.
 *
 * The role is computed from the five domain scores (same logic as the report),
 * so the shared link previews the user's animal via the prerendered
 * /share/<roleId> shell and its per-role og:image (public/og/role-<roleId>.png).
 * The scores ride along in ?r= so the landing can render the full result.
 */
import { computeRole } from './role-scoring'
import { encodeScores } from './share-url'

/** Valid role ids R01..R12. */
export const ROLE_IDS = Array.from({ length: 12 }, (_, i) => `R${String(i + 1).padStart(2, '0')}`)

/** True if id is a known role id. */
export function isRoleId(id) {
  return ROLE_IDS.includes(id)
}

/** Per-role Open Graph image path (1200x630, generated by generate_role_og_images.mjs). */
export function roleOgImage(roleId) {
  return `/og/role-${isRoleId(roleId) ? roleId : 'R01'}.png`
}

/**
 * buildSharePath — "/share/<roleId>?r=<encodedScores>" for a set of scores.
 * @param {Record<string, number>} scores
 * @returns {string}
 */
export function buildSharePath(scores) {
  const { role } = computeRole(scores)
  return `/share/${role}?r=${encodeScores(scores)}`
}

/**
 * shareResult — share a result via the Web Share API, falling back to copying
 * the link to the clipboard. The shared URL is the per-role /share landing so
 * the preview shows the user's animal.
 * @param {Record<string, number>} scores
 * @param {(key: string, opts?: object) => string} t  react-i18next translator
 * @param {() => void} [onCopied]  called after a successful clipboard fallback
 */
export function shareResult(scores, t, onCopied) {
  if (typeof window === 'undefined') return
  const { role } = computeRole(scores)
  const roleName = t(`roles.${role}.name`)
  const url = `${window.location.origin}${buildSharePath(scores)}`
  const data = {
    title: t('share.title', { role: roleName }),
    text: t('share.text', { role: roleName }),
    url,
  }
  if (navigator.share) {
    navigator.share(data).catch(() => {})
  } else if (navigator.clipboard) {
    navigator.clipboard.writeText(url).then(() => onCopied?.()).catch(() => {})
  }
}
