#!/usr/bin/env python3
"""Turn the reviewed German article files into one SQL migration.

The language pass writes one file per slug in the shape:

    TITLE_DE: ...
    DESC_DE: ...

    ---BODY_DE---
    <markdown>

This script reads those files and emits a migration that updates only the
'de' key of title, description and content on blog_posts, leaving every
other language untouched. Generating the SQL here rather than asking the
reviewers for SQL keeps the quoting in one deterministic place.

Usage:
    python3 scripts/build_de_language_migration.py <out_dir> <migration_path>
"""
import json
import pathlib
import sys

MARKER = "---BODY_DE---"


def parse(path: pathlib.Path) -> dict | None:
    """Return {title, description, content} for one reviewed file, or None
    when the file has no German body to publish."""
    text = path.read_text()
    if MARKER not in text:
        print(f"  skip (no body marker): {path.name}")
        return None
    head, body = text.split(MARKER, 1)

    title = desc = ""
    for line in head.splitlines():
        if line.startswith("TITLE_DE:"):
            title = line[len("TITLE_DE:"):].strip()
        elif line.startswith("DESC_DE:"):
            desc = line[len("DESC_DE:"):].strip()

    body = body.strip("\n")
    if not (title and body):
        print(f"  skip (empty title or body): {path.name}")
        return None
    return {"title": title, "description": desc, "content": body}


def quote(value: str) -> str:
    """A PostgreSQL string literal. json.dumps gives us a JSON scalar; the
    outer SQL quoting only has to double any single quote."""
    return "'" + json.dumps(value, ensure_ascii=False).replace("'", "''") + "'"


def main() -> int:
    out_dir = pathlib.Path(sys.argv[1])
    target = pathlib.Path(sys.argv[2])

    statements = []
    skipped = 0
    for path in sorted(out_dir.glob("*.md")):
        parsed = parse(path)
        if parsed is None:
            skipped += 1
            continue
        slug = path.stem
        statements.append(
            "UPDATE blog_posts SET\n"
            f"  title       = jsonb_set(title,       '{{de}}', {quote(parsed['title'])}::jsonb),\n"
            f"  description = jsonb_set(description, '{{de}}', {quote(parsed['description'])}::jsonb),\n"
            f"  content     = jsonb_set(content,     '{{de}}', {quote(parsed['content'])}::jsonb),\n"
            "  updated_at  = now()\n"
            f"WHERE slug = '{slug}';"
        )

    header = (
        "-- German language pass: native-editor review of every German article.\n"
        "--\n"
        "-- Only the 'de' key of title, description and content changes. The pass\n"
        "-- fixed machine-translation artefacts (Anglicisms, English word order,\n"
        "-- English title case, wrong gender on \"die Big Five\"), applied the\n"
        "-- project's no-em-dash rule, and enforced Zeuge/Zeugin over Beobachter\n"
        "-- for the peer-rating concept. Facts, numbers, DOIs and links are\n"
        "-- unchanged; markdown structure is identical to the source.\n"
        "--\n"
        f"-- Generated by scripts/build_de_language_migration.py from {len(statements)} reviewed articles.\n\n"
        "BEGIN;\n\n"
    )
    target.write_text(header + "\n\n".join(statements) + "\n\nCOMMIT;\n")
    print(f"wrote {target} with {len(statements)} updates ({skipped} skipped)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
