#!/usr/bin/env python3
"""Replace English Cercol dimension names left in translated bodies.

# Spec: docs/policies/translation.md

The policy says Cercol's own dimension names go in the target language
everywhere, and the glossary carries the mapping. Six reviewers of the German
corpus each inferred a different rule before that was written down, so the
corpus still carries "Bond" in Spanish sentences, "Depth" in Danish ones, and
so on: 165 article-language pairs at the last count.

Only three of the five names are safe to substitute mechanically.

  Bond, Depth, Presence   unmistakably English here
  Vision                  identical in several target languages
  Discipline              a real word in French and close to it elsewhere

So Vision and Discipline are left alone: a substitution that cannot tell the
Cercol dimension from the ordinary noun would corrupt sentences that were
already correct.

Words are matched with boundaries so "Bond" does not fire inside "Bonduelle",
and the academic factor names are checked before and after: Agreeableness is
the factor Bond maps onto, and it must never move.

Usage:
    python3 scripts/normalise_dimensions.py           # report
    python3 scripts/normalise_dimensions.py --sql out.sql
"""
from __future__ import annotations

import json
import os
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
LANGS = ["ca", "es", "fr", "de", "da"]

# The three that carry no ambiguity in any target language.
SAFE = ["Bond", "Depth", "Presence"]

# These must survive untouched: they are the academic factors, required in
# English on the blog, not Cercol's dimension names.
PROTECTED = ("Agreeableness", "Conscientiousness", "Extraversion",
             "Openness", "Neuroticism", "Big Five", "Big-Five")


def target_names(lang: str) -> dict[str, str]:
    """English dimension name -> the name this locale uses."""
    en = json.loads((ROOT / "src/locales/en.json").read_text())["fmDomains"]
    tg = json.loads((ROOT / f"src/locales/{lang}.json").read_text())["fmDomains"]
    return {en[k]["name"]: tg[k]["name"] for k in en}


def convert(text: str, mapping: dict[str, str]) -> tuple[str, int]:
    hits = 0
    for src in SAFE:
        dst = mapping.get(src)
        if not dst or dst == src:
            continue
        # No hyphen in the boundary: "high-Bond" should convert too.
        text, n = re.subn(rf'(?<![\w-]){src}(?![\w-])', dst, text)
        hits += n
    return text, hits


def main() -> int:
    dsn = os.environ.get("DATABASE_URL")
    rows = json.loads(subprocess.run(
        ["ssh", "-o", "BatchMode=yes", "root@188.245.60.20",
         'cd /tmp && sudo -u postgres psql -d cercol -tA -c '
         '"SELECT json_agg(json_build_object(\'slug\',slug,\'content\',content) '
         'ORDER BY slug)::text FROM blog_posts;"'],
        capture_output=True, text=True).stdout)

    changes, total = {}, 0
    for row in rows:
        for lang in LANGS:
            body = (row["content"] or {}).get(lang)
            if not body:
                continue
            before = {p: body.count(p) for p in PROTECTED}
            new, n = convert(body, target_names(lang))
            if not n:
                continue
            after = {p: new.count(p) for p in PROTECTED}
            if before != after:
                print(f"  REFUSED {row['slug']} [{lang}]: a protected term moved")
                continue
            changes[f"{row['slug']}|{lang}"] = new
            total += n
    print(f"{len(changes)} article-language pairs, {total} names replaced")

    if "--sql" in sys.argv:
        out = ["-- generated by scripts/normalise_dimensions.py\n\nBEGIN;\n"]
        for key, body in changes.items():
            slug, lang = key.split("|")
            lit = "'" + json.dumps(body, ensure_ascii=False).replace("'", "''") + "'"
            out.append(f"UPDATE blog_posts SET content = jsonb_set(content, '{{{lang}}}', {lit}::jsonb),\n"
                       f"       updated_at = now()\n WHERE slug = '{slug}';")
        out.append("\nCOMMIT;")
        pathlib.Path(sys.argv[sys.argv.index("--sql") + 1]).write_text("\n".join(out) + "\n")
        print("sql written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
